# Generated by Django 4.1.5 on 2023-02-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='unlikes',
        ),
    ]
